name: SonarQube Quality Gate Check
runs:
  using: "composite"
  steps:
    - id: quality-gate-check
      run: $GITHUB_ACTION_PATH/script/check-quality-gate.sh "${{ inputs.scanMetadataReportFile  }}" "${{ inputs.pollingTimeoutSec }}"
      shell: bash
inputs:
  scanMetadataReportFile:
    required: false
    default: .sonarqube/out/.sonar/report-task.txt
  pollingTimeoutSec:
    required: false
    default: "300"
outputs:
  quality-gate-status:
    description: >
      The resulting Quality Gate Status value of PASSED, WARN or FAILED
    value: ${{ steps.quality-gate-check.outputs.quality-gate-status }}