name: SonarQube Scan

on:
  workflow_call:
    secrets:
      GIT_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
    

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: bash
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner

      - name: Build and analyze
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: bash
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"palash150403_composite-actions" /o:"palash150403" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Install jq
        run: sudo apt-get install -y jq

 
      - name: Check SonarQube Quality Gate Status
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          reportTaskFile=".sonarqube/out/.sonar/report-task.txt"
          if [ ! -f "$reportTaskFile" ]; then
            echo "SonarQube report task file not found."
            exit 1
          fi

          # Extract ceTaskUrl from report-task.txt
          ceTaskUrl=$(grep -oP '(?<=ceTaskUrl=).*' "$reportTaskFile")
          echo "Computed ceTaskUrl: $ceTaskUrl"

          # Polling for task completion
          echo "Polling SonarQube task for completion..."
          timeout=600  # Maximum wait time (10 minutes)
          interval=10  # Polling interval (10 seconds)
          elapsed=0
          status="PENDING"
          while [ "$status" != "SUCCESS" ] && [ "$elapsed" -lt "$timeout" ]; do
            response=$(curl -s -u "$SONAR_TOKEN:" "$ceTaskUrl")
            status=$(echo "$response" | jq -r '.task.status')
            echo "Task status: $status"
            if [ "$status" == "FAILED" ]; then
              echo "SonarQube task failed!"
              exit 1
            fi
            sleep "$interval"
            elapsed=$((elapsed + interval))
          done

          if [ "$status" != "SUCCESS" ]; then
            echo "SonarQube task did not complete within the timeout."
            exit 1
          fi

          # Extract analysisId from task response
          analysisId=$(echo "$response" | jq -r '.task.analysisId')
          echo "Analysis ID: $analysisId"

          # Fetch Quality Gate status
          qualityGateUrl="https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId"
          qualityGateResponse=$(curl -s -u "$SONAR_TOKEN:" "$qualityGateUrl")
          echo "Quality Gate Response: $qualityGateResponse"

          qualityGateStatus=$(echo "$qualityGateResponse" | jq -r '.projectStatus.status')
          echo "Quality Gate Status: $qualityGateStatus"

          if [ "$qualityGateStatus" == "OK" ]; then
            echo "Quality Gate passed!"
            exit 0
          else
            echo "Quality Gate failed!"
            exit 1
          fi

