on:
  workflow_call:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SonaCloud Scan
      id: sonar_scan
      uses: ./.github/actions/ 
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sonar_token: ${{ secrets.SONAR_TOKEN }}

    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        pollingTimeoutSec: 600
        scanMetadataReportFile: .sonarqube/out/.sonar/report-task.txt
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  
    - name: Assign Quality Gate Status to variable
      run: |
        QUALITY_GATE_STATUS="${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
        echo "QUALITY_GATE_STATUS=${QUALITY_GATE_STATUS}" >> $GITHUB_ENV
        echo "The Quality Gate status is $QUALITY_GATE_STATUS"

    - name: Check if Quality Gate Passed
      run: |
        if [[ "${QUALITY_GATE_STATUS}" != "PASSED" ]]; then
          echo "Quality Gate failed with status: $QUALITY_GATE_STATUS"
          exit 1  
        else
          echo "Quality Gate passed with status: $QUALITY_GATE_STATUS"
        fi
 
    - name: "Example show SonarQube Quality Gate Status value"
      run: echo "The Quality Gate status is $QUALITY_GATE_STATUS"