name: .NET

on:
  push:
    branches: 
      - develop
      - release
    tags:
      - '*'
  
env:
  PROJECT_PATH: 'git-nexus-task/helloworld.csproj'
  PACKAGE_OUTPUT_DIR: './bin/Release'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate Tag and Branch
      id: validate_tag
      run: |
        echo "Checking GITHUB_REF: $GITHUB_REF"
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
          git fetch origin
          
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            MAIN_COMMIT=$(git rev-parse origin/main)
            if [[ "$TAG_COMMIT" != "$MAIN_COMMIT" ]]; then
              echo "Error: Tags on 'main' branch must point to the latest commit."
              exit 1
            fi
          elif [[ "${GITHUB_REF_NAME}" == "develop" || "${GITHUB_REF_NAME}" == "release" ]]; then
            echo "Error: Tags cannot be created on 'develop' or 'release' branches."
            exit 1
          else
            echo "Error: Invalid branch for tagging."
            exit 1
          fi
        else
          echo "No tag detected, proceeding with pipeline."
        fi

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: 'Restore packages'
      run: dotnet restore 

    - name: 'Build packages'
      run: dotnet build --no-restore --configuration Release
    
    - name: 'Pack packages'
      run: dotnet pack --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIR }}

    - name: 'Push Packages'
      run: |
        dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIR }}/*.nupkg --source ${{ vars.NEXUS_URL_RELEASE }} --api-key ${{ secrets.NEXUS_API_KEY }} 

      env:
        NEXUS_URL_RELEASE: ${{ vars.NEXUS_URL_RELEASE }} 
        NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
