name: .NET

on:
  push:
    branches: 
      - develop
      - release
    tags:
      - '*'
  
env:
  PROJECT_PATH: 'git-nexus-task/helloworld.csproj'
  PACKAGE_OUTPUT_DIR: './bin/Release'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Verify commit tagging policy
      id: verify-commit-tag
      run: |
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        TAG_EXISTS=$(git tag --points-at HEAD)
        
        echo "Branch: $BRANCH_NAME"
        echo "Tag exists: $TAG_EXISTS"
        
        if [[ "$BRANCH_NAME" == "develop" || "$BRANCH_NAME" == "release" ]]; then
          if [[ -n "$TAG_EXISTS" ]]; then
            echo "Error: Tagged commit on $BRANCH_NAME branch is not allowed."
            exit 1
          fi
        elif [[ "$BRANCH_NAME" == "main" ]]; then
          if [[ -z "$TAG_EXISTS" ]]; then
            echo "Error: Tagged commit is required on main branch."
            exit 1
          fi
        else
          echo "Error: Unknown branch. Exiting."
          exit 1
        fi
      shell: bash

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: 'Restore packages'
      run: dotnet restore 

    - name: 'Build packages'
      run: dotnet build --no-restore --configuration Release
    
    - name: 'Pack packages'
      run: dotnet pack --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIR }}

    - name: 'Push Packages'
      run: |
        dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIR }}/*.nupkg --source ${{ vars.NEXUS_URL_RELEASE }} --api-key ${{ secrets.NEXUS_API_KEY }} 

      env:
        NEXUS_URL_RELEASE: ${{ vars.NEXUS_URL_RELEASE }} 
        NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
