name: .NET

on:
  push:
    branches: 
      - develop
      - release
    tags:
      - '*'
  
env:
  PROJECT_PATH: 'git-nexus-task/helloworld.csproj'
  PACKAGE_OUTPUT_DIR: './bin/Release'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 'Check branch and tag logic'
      run: |
        echo "REF: ${{ github.ref }}"
        echo "BRANCH: ${{ github.ref_name }}"
        if [[ "${{ github.ref }}" =~ ^refs/tags/ ]]; then
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Tag is on the main branch. Proceeding with pipeline."
          else
            echo "Error: Tag is on an unsupported branch (${BRANCH}). Failing the pipeline."
            exit 1
          fi
        else
          echo "Not a tag. Proceeding with pipeline."
        fi

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: 'Restore packages'
      run: dotnet restore 

    - name: 'Build packages'
      run: dotnet build --no-restore --configuration Release
    
    - name: 'Pack packages'
      run: dotnet pack --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIR }}

    - name: 'Push Packages'
      run: |
        dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIR }}/*.nupkg --source ${{ vars.NEXUS_URL_RELEASE }} --api-key ${{ secrets.NEXUS_API_KEY }} 

      env:
        NEXUS_URL_RELEASE: ${{ vars.NEXUS_URL_RELEASE }} 
        NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
